### ISSUE TITLE
reference paper

### ISSUE THREAD

**Issue by SweetPin** [rishab26201/Pursuit-Evasion#1]
Hello, do you have any reference papers on the methods used in your code？If you have any, please let me know. I'd like to have a further study.Thank you!

**Comment by rishabbala** [comment]
Hey,

I referred to the paper "Guaranteed decentralized pursuit-evasion in the plane with multiple pursuers" for most of the work on Voronoi algorithm.

**Comment by SweetPin** [comment]
Thank you!But is there another paper based on geometric method?

**Comment by SweetPin** [comment]
Thank you!But sorry to bother you again. Do you have any reference papers based on the new geometric algorithm?In fact, my main problem is geometric algorithm. I'm sorry I didn't make it clear before.
