### ISSUE TITLE
reference paper

### ISSUE THREAD

**Issue by SweetPin** [rishab26201/Pursuit-Evasion#2]
Thank you!But sorry to bother you again. Do you have any reference papers based on the new geometric algorithm?In fact, my main problem is geometric algorithm. I'm sorry I didn't make it clear before.

**Comment by rishabbala** [comment]
Hey, sorry no, I dont have any material for that. It was just something I was trying out

**Comment by SweetPin** [comment]
That's a pity, but thank you very much
